on: [push]

name: CI

jobs:
  build_and_test:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Start minio
        run: |
          docker run -d \
                    -p 9000:9000 \
                    --name minio \
                    minio/minio:latest server /data
      - uses: actions-rs/cargo@v1
        name: Format
        with:
          command: fmt
          args: --all --check
      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --all --all-targets --all-features
      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: --all --all-targets --all-features  --  -D warnings